name: build & verify
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build main branch
    runs-on: ubuntu-latest
    permissions: #
      contents: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: "gradle"

      - name: Verify
        run: ./gradlew clean build --no-daemon

      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          use-gradlew: true
          gradle-build-module: |-
            :app
          gradle-build-configuration: |-
            compileClasspath
